listeners.tcp.default = 5672
management.tcp.port = 15672
prometheus.tcp.port = 15692
prometheus.return_per_object_metrics = true

# Keep default development behavior convenient, but prefer the ping user in README.
loopback_users.guest = false
